### PR TITLE
✨  Create a yaml parser random forest address model

### PR DESCRIPTION
**Pull request by LeoSilvaGomes**
## Motivation
Create a parser to yaml to return the configs to run the model

### Yaml output

```
[{
    'model': 'keyboard_smash', 
    'type': 'address', 
    'columns_set_alias': ['tudo_junto'], 
    'keyboard_smash': {
         'tudo_junto': {
              'ksmash_sequence_vowels': 1.0, 
              'ksmash_sequence_consonants': 1.999, 
              'ksmash_sequence_special_characters': 2.2499, 
              'ksmash_numbers': 2.9, 
              'ksmash_char_frequence': 2.78
          }
     }, 
    'n_estimators': 100, 
    'test_size': 0.3
}]
```

### Default values
```
'ksmash_sequence_vowels': 1.0, 
'ksmash_sequence_consonants': 1.999, 
'ksmash_sequence_special_characters': 2.2499, 
'ksmash_numbers': 2.9, 
'ksmash_char_frequence': 2.78
'n_estimators': 100, 
'test_size': 0.3
```

## Changes

- Adjust `codeowners`
- Adjust `main.py` to run correctly

## Status Checklist

- [x] Test

## Screenshots

|Output|
|---|
|image|

## Testing

- Execute ```python src/main.py```

### CODE REVIEW

**Comment by apmt** [comment]
I guess a simpler structure to the parsers would be all in the same directory, like that:
```
parser
|_ feature_engineering_parser.py
|_ YAML_parser.py
|_ model_parser.py
```
this makes the file searching easier, what do you think @LeoSilvaGomes ?

**Comment by apmt** [comment]
I guess it's a good thing to change the  alias "tudo_junto" and "apenas_number" for english ones, like: "example_alias_1" or "example_name_2"

**Comment by apmt** [comment]
I'm receiving the following error when trying to run `python src/main.py`:

```
Traceback (most recent call last):
  File "src/main.py", line 3, in <module>
    from src.parser.initial.parser import YAMLParser
ModuleNotFoundError: No module named 'src'
```

**Comment by LeoSilvaGomes** [comment]
> I'm receiving the following error when trying to run `python src/main.py`:
> 
> ```
> Traceback (most recent call last):
>   File "src/main.py", line 3, in <module>
>     from src.parser.initial.parser import YAMLParser
> ModuleNotFoundError: No module named 'src'
> ```

This is happening because the import is related to the test, I will solve this, but I don't know how yet :P

**Review by apmt — APPROVED** [review]
awesome!

**Pull request merged**
